lang: c
script: ./travis-ci.sh
env:
  secure: "bUmxH62/NcBGK0p9a17M0KnSV1lyHxNVGBZoHLM/g8RiK1ZXY1Ol8FI2tWQI3SOI7qNh5QPr4AV889sKbt2bImln3UurxXLpMvTnR8s8szxP1PpuLWnJrcB6WihUi/PNehgj7QGqGComqvQt4VQ+KschOiCtCpzvQ6ixDONm/CNuC8zfXb5BeRJ8ZLBnEQCkcBy+LoaCxiM2PKg2YM0aXd9vkHov8/NVmjHHo0Wfh78lorycHPgCvXMXfvQbcRJ1OmBMlyG2KmLssejibGvv9Q5yqvSInSfPYFnsSVkIQeQMMzvrxXCfp0B6CFYpqpIsP9cXygbeJT0a3WAxBKA4E581xvpfwfHXeQ7/1UI9H5tn+zvyLy+NvigDKA7JBAtRiyAJ+kQ+PSFDMZqWJIsglNgTcKccFMqxoC0d1CPwfz2gF7PEgh1wMdkE8+uazdZecwpWXEO9QnUgXlcapkilzfjKdx910lFvNy7epNwScqduqxgNbKdz95QN6ND2IBxkI2TgbJCpTkRBaJ8C2XCF2gXHCGSDaKHna5GHpQsiArk+kDwaBbv9uCP1KhCkGSQi5CuiCwkTQsFjF/qJFCYd5hyxev86ZHn1yuaCc4DRPUCBuN4X1+yDUJPBq0wXZEHlIjq9c8WrsjEOMnjfgoikzHsaNv5L8GnOBDHMnF5hf7g="
notifications:
  irc:
    - "irc.freenode.org#rerun"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq markdown
 - sudo apt-get install -qq build-essential
 - sudo apt-get install -qq devscripts
 - sudo apt-get install -qq dh-make    
 - sudo apt-get install -qq rpm    
